### PR TITLE
Added support for CocoaPods 0.36 & Swift frameworks.

### PR DESCRIPTION
**Pull request by fluidsonic**
Added a `module.modulemap` file which describes the framework and which Xcode requires for true frameworks to work correctly.

When using LayerKit with the upcoming version of CocoaPods (which supports Swift) this addition is also necessary or otherwise the project will no longer work for everyone.

For more details see discussion @ https://github.com/CocoaPods/swift/issues/4#issuecomment-66914260

### CODE REVIEW

**Comment by fluidsonic** [comment]
@blakewatters any news on this?

**Comment by blakewatters** [comment]
Hey Marc -

This didn’t make it onto my radar because there wasn’t a requested tracked through the support channel. I’ve opened up an issue on this and will try to get this in today for v0.9.3

If you have further requests (or PR’s!) in the future, shoot a note to support@layer.com to ensure a ticket gets opened up tracking the item and it won’t fall through the cracks.

Cheers,
Blake

**Comment by blakewatters** [comment]
@fluidsonic I’ve updated our release tooling to generate the umbrella header and include it with the built framework. If you’d like, I can drop you a pre-release of v0.9.3 that includes the functionality. Full release should be available early this week.

**Comment by fluidsonic** [comment]
@blakewatters This issue is about a missing modulemap, not a missing umbrella header :)

**Comment by blakewatters** [comment]
Shipped v0.9.3

**Pull request closed without merging**
